### 가우시안 나이브 베이즈 
- 결과값 범주형 데이터 연속형일때(ex)아이리스데이터)

In [9]:
import numpy as np
import pandas as pd


In [3]:
from sklearn.datasets import load_iris
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['Species'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Species  
0        0  
1        0  
2        0  
3        0  
4        0

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, :4],
                                                   df.iloc[:, 4],
                                                   test_size = 0.33,
                                                   stratify = df.Species,
                                                   random_state = 234)
from sklearn.naive_bayes import GaussianNB
gaussian_model = GaussianNB().fit(X_train, y_train)

In [5]:
from sklearn.metrics import classification_report, confusion_matrix
pred = gaussian_model.predict(X_test)
print(classification_report(y_test, pred))
print(confusion_matrix(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.94      0.88      0.91        17
           2       0.88      0.94      0.91        16

    accuracy                           0.94        50
   macro avg       0.94      0.94      0.94        50
weighted avg       0.94      0.94      0.94        50

[[17  0  0]
 [ 0 15  2]
 [ 0  1 15]]


In [6]:
def rateMean(v1, v2):
    return 2 / (1/v1 + 1/v2)
rateMean(.94, .88)

0.9090109890109889

In [7]:
gaussian_model.sigma_ # devide by n  분산

array([[0.13682278, 0.11603306, 0.04110193, 0.01280074],
       [0.1800551 , 0.09682278, 0.20844812, 0.03941231],
       [0.33481834, 0.10297578, 0.26616782, 0.07810554]])

In [8]:
gaussian_model.theta_ #   평균

array([[4.98787879, 3.41818182, 1.46363636, 0.24848485],
       [5.84545455, 2.78787879, 4.20606061, 1.32424242],
       [6.55588235, 2.97647059, 5.50294118, 2.02058824]])

In [11]:
X_train.groupby(y_train).agg(['mean', 'var']) # devide by n-1

sepal length (cm)           sepal width (cm)            \
                     mean       var             mean       var   
Species                                                          
0                4.987879  0.141098         3.418182  0.119659   
1                5.845455  0.185682         2.787879  0.099848   
2                6.555882  0.344964         2.976471  0.106096   

        petal length (cm)           petal width (cm)            
                     mean       var             mean       var  
Species                                                         
0                1.463636  0.042386         0.248485  0.013201  
1                4.206061  0.214962         1.324242  0.040644  
2                5.502941  0.274234         2.020588  0.080472

In [10]:
var1 = lambda x: np.var(x, ddof=0)

In [15]:
X_train.groupby(y_train).agg([('평균', 'mean'), ('분산', var1)]) # devide by n-1

sepal length (cm)           sepal width (cm)            \
                       평균        분산               평균        분산   
Species                                                          
0                4.987879  0.136823         3.418182  0.116033   
1                5.845455  0.180055         2.787879  0.096823   
2                6.555882  0.334818         2.976471  0.102976   

        petal length (cm)           petal width (cm)            
                       평균        분산               평균        분산  
Species                                                         
0                1.463636  0.041102         0.248485  0.012801  
1                4.206061  0.208448         1.324242  0.039412  
2                5.502941  0.266168         2.020588  0.078106