In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('ThoraricSurgery.csv',header=None)
df.head()

0   1     2     3   4   5   6   7   8   9   10  11  12  13  14  15  16  17
0  293   1  3.80  2.80   0   0   0   0   0   0  12   0   0   0   1   0  62   0
1    1   2  2.88  2.16   1   0   0   0   1   1  14   0   0   0   1   0  60   0
2    8   2  3.19  2.50   1   0   0   0   1   0  11   0   0   1   1   0  66   1
3   14   2  3.98  3.06   2   0   0   0   1   1  14   0   0   0   1   0  80   1
4   17   2  2.21  1.88   0   0   1   0   0   0  12   0   0   0   1   0  56   0

In [3]:
pdf = df
pdf.columns = ['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18']
pdf.head()

1  2     3     4  5  6  7  8  9  10  11  12  13  14  15  16  17  18
0  293  1  3.80  2.80  0  0  0  0  0   0  12   0   0   0   1   0  62   0
1    1  2  2.88  2.16  1  0  0  0  1   1  14   0   0   0   1   0  60   0
2    8  2  3.19  2.50  1  0  0  0  1   0  11   0   0   1   1   0  66   1
3   14  2  3.98  3.06  2  0  0  0  1   1  14   0   0   0   1   0  80   1
4   17  2  2.21  1.88  0  0  1  0  0   0  12   0   0   0   1   0  56   0

In [4]:
x = df.iloc[:,:-1].values
y = df['18'].values
x.shape, y.shape

((470, 17), (470,))

In [5]:
np.unique(y, return_counts=True)

(array([0, 1], dtype=int64), array([400,  70], dtype=int64))

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    x, y , stratify=y, test_size=0.2, random_state=2021
) 
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((376, 17), (94, 17), (376,), (94,))

In [7]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=2020)


In [8]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier(random_state=2020)

In [9]:
pred =dtc.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.7659574468085106

In [11]:
dtc.score(X_test, y_test) ## accuracy_score(y_test, pred)

0.7659574468085106

In [12]:
from sklearn.metrics import precision_score
precision_score(y_test, pred)

0.2777777777777778

In [13]:
from sklearn.metrics import recall_score
recall_score(y_test, pred)

0.35714285714285715

In [14]:
from sklearn.metrics import f1_score
f1_score(y_test, pred)

0.31250000000000006

In [15]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[67, 13],
       [ 9,  5]], dtype=int64)

In [16]:
from sklearn.ensemble import RandomForestClassifier
rfc2 = RandomForestClassifier(random_state=2021)

In [17]:
accuracy_score(y_test, pred_rf)

NameError: name 'pred_rf' is not defined

In [ ]:
rfc2.fit(X_train, y_train)

RandomForestClassifier(random_state=2021)

In [ ]:
pred_rf = rfc2.predict(X_test)
confusion_matrix(y_test, pred_rf)

array([[80,  0],
       [14,  0]], dtype=int64)

In [ ]:
dtc.score(X_test, y_test)

0.6808510638297872

In [ ]:
params= {
    'max_depth':[2,3,4,5,6],
    'min_samples_split':[2,3,4,5,6]
}

In [ ]:
from sklearn.model_selection import GridSearchCV

grid_dt = GridSearchCV(dtc, param_grid=params, scoring='accuracy', cv=3)
grid_dt.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [2, 3, 4, 5, 6],
                         'min_samples_split': [2, 3, 4, 5, 6]},
             scoring='accuracy')

In [ ]:
grid_dt.best_params_

{'max_depth': 2, 'min_samples_split': 2}

In [ ]:
params= {
    'max_depth':[2,3],
    'min_samples_split':[2,3]
}

In [ ]:
grid_dt = GridSearchCV(dtc, param_grid=params, scoring='accuracy', cv=3)  #정확도
grid_dt.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [2, 3], 'min_samples_split': [2, 3]},
             scoring='accuracy')

In [ ]:
grid_dt.best_params_

{'max_depth': 2, 'min_samples_split': 2}

In [ ]:
grid_dt.best_score_

0.8324867724867725

In [ ]:
best_dt = grid_dt.best_estimator_
best_dt.score(X_test, y_test)

0.8297872340425532

In [ ]:
params= {
    'max_depth':[2,3,4,5,6],
    'min_samples_split':[2,3,4,5,6]
}

In [ ]:
grid_dt = GridSearchCV(dtc, param_grid=params, scoring='precision', cv=3)  #정밀도
grid_dt.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [2, 3, 4, 5, 6],
                         'min_samples_split': [2, 3, 4, 5, 6]},
             scoring='precision')

In [ ]:
grid_dt.best_params_

{'max_depth': 4, 'min_samples_split': 6}

In [ ]:
params= {
    'max_depth':[2,3,4,5,6],
    'min_samples_split':[4,5,6,7,8]
}

In [ ]:
grid_dt = GridSearchCV(dtc, param_grid=params, scoring='precision', cv=3)
grid_dt.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [2, 3, 4, 5, 6],
                         'min_samples_split': [4, 5, 6, 7, 8]},
             scoring='precision')

In [ ]:
grid_dt.best_params_

{'max_depth': 4, 'min_samples_split': 6}

In [ ]:
grid_dt.best_score_

0.1976190476190476

In [ ]:
best_dt = grid_dt.best_estimator_
best_dt.score(X_test, y_test)

0.8191489361702128

In [ ]:
params= {
    'max_depth':[2,3,4,5,6],
    'min_samples_split':[2,3,4,5,6]
}

In [ ]:
grid_dt = GridSearchCV(dtc, param_grid=params, scoring='recall', cv=3)  #재현율
grid_dt.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [2, 3, 4, 5, 6],
                         'min_samples_split': [2, 3, 4, 5, 6]},
             scoring='recall')

In [ ]:
grid_dt.best_params_


{'max_depth': 6, 'min_samples_split': 4}

In [ ]:
params= {
    'max_depth':[5,6,7,8],
    'min_samples_split':[2,3,4,5,6]
}

In [ ]:
grid_dt = GridSearchCV(dtc, param_grid=params, scoring='recall', cv=3)
grid_dt.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [5, 6, 7, 8],
                         'min_samples_split': [2, 3, 4, 5, 6]},
             scoring='recall')

In [ ]:
grid_dt.best_params_

{'max_depth': 7, 'min_samples_split': 2}

In [ ]:
grid_dt.best_score_

0.17836257309941517

In [ ]:
best_dt = grid_dt.best_estimator_
best_dt.score(X_test, y_test)

0.7872340425531915

In [ ]:
params= {
    'max_depth':[2,3,4,5,6],
    'min_samples_split':[2,3,4,5,6]
}

In [ ]:
grid_dt = GridSearchCV(dtc, param_grid=params, scoring='f1', cv=3)
grid_dt.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [2, 3, 4, 5, 6],
                         'min_samples_split': [2, 3, 4, 5, 6]},
             scoring='f1')

In [ ]:
grid_dt.best_params_

{'max_depth': 6, 'min_samples_split': 4}

In [ ]:
params= {
    'max_depth':[5,6,7,8],
    'min_samples_split':[2,3,4,5,6]
}

In [ ]:
grid_dt.best_params_

{'max_depth': 6, 'min_samples_split': 4}

In [ ]:
grid_dt.best_score_

0.10782556750298684

In [ ]:
best_dt = grid_dt.best_estimator_
best_dt.score(X_test, y_test)

0.776595744680851